[package]
name = "shikataganai"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "*"
wgpu = "*"
toml = "*"
image = "*"
imgui = "*"
winit = "*"
serde = "*"
bytemuck = "*"
imgui-sys = "*"
num-traits = "*"
imgui-wgpu = "*"
futures-lite = "*"
bytemuck_derive = "*"
bevy_framepace = { git = "https://github.com/aevyrie/bevy_framepace", branch = "main" }
imgui-winit-support = { version = "*", default-features = false, features = [ "winit-26" ] }

[features]
default = []
trace = ["bevy/trace", "bevy/trace_tracy"]

[dependencies.bevy_embedded_assets]
git = "https://github.com/Nhlest/bevy_embedded_assets"
branch = "main"

[dependencies.bevy_rapier3d]
git = "https://github.com/Nhlest/bevy_rapier"
branch = "master"
default-features = false
features = ["simd-stable", "dim3"]

[dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
branch = "main"
default-features = false
features = ["bevy_winit", "png", "jpeg", "bevy_render", "bevy_core_pipeline"]

[profile.dev]
opt-level = 1
overflow-checks = false

[profile.dev.package."*"]
opt-level = 3
overflow-checks = false