[package]
resolver = "2"
name = "shikataganai_common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.*"
bevy_renet = "0.0.6"
noise = "0.8.*"

[dependencies.bevy]
version = "0.9.*"
default-features = false
features = []