name: Release tagged build

on:
  push:
    tags:
      - '*'

jobs:
  compile:
    name: ${{ matrix.arch.target }}
    runs-on: ${{ matrix.arch.os }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - { os: 'ubuntu-latest',  target: 'x86_64-unknown-linux-gnu', ext: '' , env: ''}
          - { os: 'macOS-latest',   target: 'x86_64-apple-darwin', ext: '' , env: '' }
          - { os: 'macOS-latest',   target: 'aarch64-apple-darwin', ext: '' , env: 'CMAKE_APPLE_SILICON_PROCESSOR=arm64 CMAKE_SYSTEM_PROCESSOR=arm64 CMAKE_HOST_SYSTEM_PROCESSOR=arm64 CMAKE_CXX_FLAGS="-mcpu=apple-m1"'}
          - { os: 'windows-latest', target: 'x86_64-pc-windows-msvc', ext: '.exe' , env: '' }
    
    env:
      SOURCE_FILE_UNIX: target/${{ matrix.arch.target }}/release/shikataganai${{ matrix.arch.ext }}
      SOURCE_FILE_WIN: target\${{ matrix.arch.target }}\release\shikataganai${{ matrix.arch.ext }}
      TARGET_FILE: shikataganai-${{ matrix.arch.target }}${{ matrix.arch.ext }}

    steps:
      - uses: actions/checkout@v2

      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: ${{ matrix.arch.target }}
          override: true

      - name: export additional environment
        if: ${{ runner.os != 'Windows' && matrix.arch.env != '' }}
        run: export ${{ matrix.arch.env }}

      - name: build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target=${{ matrix.arch.target }} --release --no-default-features

      - name: rename files unix
        if: runner.os != 'Windows'
        run: mv ${{ env.SOURCE_FILE_UNIX }} ${{ env.TARGET_FILE }}

      - name: rename files windows
        if: runner.os == 'Windows'
        run: move ${{ env.SOURCE_FILE_WIN }} ${{ env.TARGET_FILE }}

      - name: upload release assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ env.TARGET_FILE }}